# 1 Getting started Exercises

# Dimension of a circle
```{r}
radius <- 1
area <- pi * radius^2
circum <- 2 * pi * radius
print(paste("Radius:", radius, " Circumference:", circum))
```

# Sequence of numbers
```{r}
seq(0, pi, length.out = 5)
```

#Gauss sum
```{r}
sum(1:100)

```
```{r}
vec_a <- 1:50
vec_b <- 100:51
vec_c <- vec_a + vec_b
sum(vec_c)
```


#Magic trick algorithm
```{r}
x <- 7
x_save <- x
x <- x + 1
x <- x * 2
x <- x + 4
x <- x / 2
x <- x - x_save
print(x)
```


#Vectors
```{r}
class(datasets::rivers)
length(datasets::rivers)
mean(datasets::rivers)
quantile(datasets::rivers, probs = 0.33)
```


#Data frames
```{r}
dim(datasets::quakes)
vec <- datasets::quakes$mag
max(vec)
idx <- which.max(vec)
datasets::quakes$long[idx]
datasets::quakes$lat[idx]
```

# 2 Programming primers

# Gauss variations
```{r}
sum <- 0
for (i in 1:100){
  sum <- sum + i
}
print(sum)

loop_status <- TRUE
counter <- 0
sum <- 0
while (loop_status){
  counter <- counter + 1
  sum <- sum + counter
  if (counter == 100) loop_status <- FALSE
}
print(sum)
```
```{r}
sum <- 0
for (i in 1:100){
  if (i %% 3 == 0 && i %% 7 == 0 ){
    sum <- sum + i
  }
}
print(paste0("the Sum of multiples of 3 and 7 within 1-100 is: ", sum))
```

# Nested loops
```{r}
mymat <- matrix(c(6, 7, 3, NA, 15, 6, 7, 
              NA, 9, 12, 6, 11, NA, 3, 
              9, 4, 7, 3, 21, NA, 6, 
              rep(NA, 7)),
            nrow = 4, byrow = TRUE)
myvec <- c(8, 4, 12, 9, 15, 6)
for (i in 1:nrow(mymat)){
  for (j in 1:ncol(mymat)){
    if (is.na(mymat[i, j])){
      mymat[i, j] <- max(myvec)
    }
  }
  myvec <- myvec[-which.max(myvec)]
}
mymat
```

# Interpolation
```{r}
vec <- rep(NA, 100)
vec[1:25] <- 6
vec[66:100] <- -20
last_non_na <- 1 
while (!is.na(vec[last_non_na+1])) last_non_na <- last_non_na + 1
first_non_na <- last_non_na + 1
while (is.na(vec[first_non_na])) first_non_na <- first_non_na + 1
last_value <- vec[last_non_na]
first_value <- vec[first_non_na]
delta <- (last_value - first_value) / (last_non_na - first_non_na)
for (i in 2:length(vec)){
  if (is.na(vec[i])) vec[i] <- vec[i-1] + delta
}

plot(vec)
```
```{r}
vec <- rep(NA, 100)
vec[1:25] <- 6
vec[66:100] <- -20
vec <- approx(1:100, vec, xout = 1:100)
plot(vec)

```

# 3 Data wrangling

# Star wars
```{r}
dplyr::starwars |>
  dplyr::filter(
    skin_color == "pale" &
      (homeworld == "Naboo" | homeworld == "Ryloth")
  ) |>
  nrow()
```
```{r}
dplyr::starwars |> 
  unnest(films) |> 
  filter(films == "Return of the Jedi") |> 
  unnest(starships) |> 
  arrange(height) |> 
  slice(1) |> 
  select(name, starships)
```


# Aggregating


